on: push
jobs: 
    third-jobs:
        runs-on: ubuntu-latest
        steps:
            - run: node --version
            - run: npm --version
            - uses: actions/checkout@v3
            - run: npm install
            - run: node index.js
            - run: npx eslint .
            
            # - run: npx jest index.js - throws
            # - run: deployment -s3 bucket -
